### PR TITLE
Adding backports.zoneinfo fall back idiom for python3 compatibility

### PR DESCRIPTION
**Pull request by nicholasrobinson**
Backports/Fallback idom:
- https://pypi.org/project/backports.zoneinfo/

### CODE REVIEW

**Comment by nicholasrobinson** [comment]
Motivation: Running HomeAssistant docker container on a Synology NAS I encountered:

```
ModuleNotFoundError: No module named 'zoneinfo'
```

This patch resolves the dependency issue for systems running in python3.

**Comment by RobertD502** [comment]
Does the Home Assistant docker container not use Python 3.9?

Have you tested that the back port allows this integration to work on your own system (I don't run HA as a standalone container)?

**Comment by nicholasrobinson** [comment]
> Does the Home Assistant docker container not use Python 3.9?

I'm running `Home Assistant Container core-2021.6.3`, which reports:

```
# python --version
Python 3.8.9
```

> The reason I ask is because [this](https://developers.home-assistant.io/blog/2021/05/07/switch-pytz-to-python-dateutil/) post by Paulus points to zoneinfo being the standard. Interesting if their docker container isn't using 3.9.

Interesting. This possibly mitigates the issue I am encountering, but I won't be able to confirm until I update my container 😬.

I'm happy to keep this PR open until I can confirm, but it might be a while until I upgrade!

**Comment by RobertD502** [comment]
Oh boy you sure are behind on updates 😅. Time to read up on all the breaking changes from .7 to 2022.2.

I believe they deprecated 3.8 in January. You should be able to manually update to 3.9 within your container if you don't want to update HA as a whole.

**Pull request closed without merging**
